# Generated by Django 3.2.7 on 2021-10-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
    ]
