# Generated by Django 3.2.7 on 2021-10-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
            ],
        ),
    ]
